theme: minima
minima:
  dark_mode: true

timezone: Europe/Helsinki # この設定が無いと　blogpost が未来と認識されて表示されない場合があった

defaults:
  - scope:
      path: "_posts"
    values:
      css: "/assets/css/styles.css"
