theme: minima
minima:
  dark_mode: true

stylesheets:
  - /assets/css/styles.css

# Jekyll configuration

name: Blog Name
description: Software Developer

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: 

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: false

social:
  github: jamad
  rss: feed.xml


# Google Analytics key, leave blank to ignore
google_analytics_key:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: jamad
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
